# This ConfigMap is used to configure a self-hosted coe-odl installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: coe-config
  namespace: kube-system
data:
  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
        "cniVersion":"0.3.0",
        "name":"odl-cni",
        "type":"odlovs-cni",
        "mgrPort":6640,
        "mgrActive":true,
        "manager":"192.168.33.1",
        "ovsBridge":"ovsbrk8s",
        "ctlrPort":6653,
        "ctlrActive":true,
        "controller":"192.168.33.1",
        "externalIntf":"",
        "externalIp":"",
        "ipam":{
            "type":"host-local",
            "subnet":"usePodCidr",
            "routes":[{
                "dst":"0.0.0.0/0"
            }]
        }
    }

---
