apiVersion: v1
kind: Service
metadata:
  labels:
    name: apacheout
    role: service
  name: apacheout
spec:
  ports:
    - port: 8801
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    name: webserver
  externalIPs:
  - 192.168.50.11

