apiVersion: v1
kind: Pod
metadata:
  name: busybox3
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox3
  restartPolicy: Always
  nodeSelector:
    ndName: minion2

