apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox-scale
  namespace: demos
spec:
  selector:
    matchLabels:
      demo: deployment
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        demo: deployment
        version: v1
    spec:
      containers:
      - name: busybox
        image: busybox
        command: 
        - sleep
        - "3600"
        volumeMounts:
        - name: content
          mountPath: /data
        imagePullPolicy: IfNotPresent
      volumes:
      - name: content
