apiVersion: v1
kind: Pod
metadata:
  name: nginxtwin
 spec:
  containers:
  - name: nginxtwin
    image: nginx
apiVersion: v1
kind: Pod
metadata:
  name: nginxtwin
  labels:
    name: webserver
spec:
  containers:
  - name: nginxtwin
    image: nginx
